### ISSUE TITLE
build fails after upgrading to 1.3.28

### ISSUE THREAD

**Issue by demetris-manikas** [yysun/apprun-site#31]
Hi. After upgrading from 1.3.26 to 1.3.28 my project fails to build with the following errors
`Build failed ENOENT: no such file or directory, copyfile '/home/demetris/tmp/apprun/preferance/pages/index.html' -> '/home/demetris/tmp/apprun/preferance/public/index.html'
[info] Serve: /about/ 
[error] Error: /about ENOENT: no such file or directory, open '/home/demetris/tmp/apprun/preferance/public/_.html'
[error] Failed:  /about ENOENT: no such file or directory, open '/home/demetris/tmp/apprun/preferance/public/_.html'
✔ Rendered /about
Error: ENOENT: no such file or directory, open '/home/demetris/tmp/apprun/preferance/public/_.html'
    at readFileSync (node:fs:448:20)`

The public directory is being deleted and not recreated is what I guess is happening.

**Comment by yysun** [comment]
Sorry about that. I was trying to compile and serve code from memory in dev
mode and broke it. Just pushed 1.3.29 to fix it.

**Comment by demetris-manikas** [comment]
No worries.
Thanks for the quick fix
