### ISSUE TITLE
npm start don't show the changes in the first refresh!

### ISSUE THREAD

**Issue by syronz** [yysun/apprun-site#4]
When running project in dev server the changes didn't show at first time and need to refresh twice.

**Comment by yysun** [comment]
There is a service worker that caches the pages. You can try to remove the sw-init.js from index.html.

**Comment by syronz** [comment]
I found another way. By checking Update on reload.
Developer Tools > Application > Service Workers, then check **Update on reload**

[screenshot](https://i.ibb.co/4ff3CJ0/Screen-Shot-2020-03-27-at-7-56-06-PM.png)
